spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/product_catalogue
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


  kafka:
    consumer:
      bootstrap-servers: dura.manicasolutions.dev:9092
      group-id: products
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
    producer:
      bootstrap-servers: dura.manicasolutions.dev:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # value-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


user:
  service:
    url: https://api.manicasolutions.dev/permissions
    auto-bid-increment: 5


topic:
  user:
    registration: user_registration
    update: user_updates
  vendor:
    vendor_updates: vendor_updates
